// Lightweight DOM simulation: exercises application initialization and event/state paths.
// This is not a browser layout or visual test.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const html=fs.readFileSync(__dirname+'/dist/index.html','utf8');
function run(saved){
let nodes=[],docListeners={},storage={};if(saved)storage['sample-household-budget-v1-local-sample']=JSON.stringify(saved);
const attrs=s=>Object.fromEntries([...s.matchAll(/([\w-]+)(?:\s*=\s*(?:"([^"]*)"|'([^']*)'))?/g)].map(m=>[m[1],m[2]??m[3]??'']));
class El{constructor(tag,a={},origin=null){this.tagName=tag.toUpperCase();this.attrs=a;this.id=a.id||'';this.dataset={};for(let[k,v]of Object.entries(a))if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=v;this._value=a.value||'';this.type=a.type||'';this.className=a.class||'';this.origin=origin;this.hidden='hidden'in a;this.disabled='disabled'in a;this.validity={badInput:false};this.listeners={};this.classList={toggle:(c,on)=>{const cs=new Set(this.className.split(' '));on?cs.add(c):cs.delete(c);this.className=[...cs].join(' ')}};this._html='';nodes.push(this)}get value(){return this._value}set value(x){this._value=String(x)}set innerHTML(v){nodes=nodes.filter(x=>x.origin!==this);this._html=v;parse(v,this);if(this.tagName==='SELECT'){const m=v.match(/<option[^>]*value="([^"]*)"/);this.value=m?m[1]:''}}get innerHTML(){return this._html}insertAdjacentHTML(_,v){const old=this.value;this.innerHTML+=v;this.value=old}set textContent(v){this._text=String(v)}get textContent(){return this._text||''}setAttribute(k,v){this.attrs[k]=String(v)}removeAttribute(k){delete this.attrs[k]}hasAttribute(k){return k in this.attrs}toggleAttribute(k,on){if(on)this.attrs[k]='';else delete this.attrs[k]}setCustomValidity(v){this.validationMessage=v}addEventListener(k,f){(this.listeners[k]??=[]).push(f)}closest(sel){return matches(this,sel)?this:null}focus(){}scrollIntoView(){}showModal(){this.open=true}close(){this.open=false}}
function parse(s,origin){for(const m of s.matchAll(/<(input|select|option|button|div|section|span|small|strong|p|nav|dialog|main|aside|tbody|a|article)\b([^>]*)>/g))new El(m[1],attrs(m[2]),origin);for(const m of s.matchAll(/<select\b([^>]*)>([\s\S]*?)<\/select>/g)){const a=attrs(m[1]),el=nodes.filter(x=>x.tagName==='SELECT'&&x.id===(a.id||'')&&x.origin===origin).at(-1);const first=m[2].match(/<option[^>]*value="([^"]*)"/);if(el){el._html=m[2];el.value=first?first[1]:''}}}
function matches(el,sel){if(sel.startsWith('[')){const m=sel.match(/^\[([^=\]]+)(?:="([^"]*)")?\]$/);return !!m&&m[1]in el.attrs&&(m[2]===undefined||el.attrs[m[1]]===m[2])}if(sel.startsWith('.'))return sel.slice(1).split('.').every(x=>el.className.split(' ').includes(x));return el.tagName.toLowerCase()===sel}
parse(html.split('<script id="budget-data"')[0],null);
for(const id of ['budget-data','budget-state']){const el=new El('script',{id});el.textContent=html.match(new RegExp('<script id="'+id+'"[^>]*>([\\s\\S]*?)<\\/script>'))[1]}
const document={getElementById:id=>nodes.filter(n=>n.id===id).at(-1)||null,querySelectorAll:q=>nodes.filter(n=>q.split(',').some(sel=>matches(n,sel))),querySelector:q=>nodes.find(n=>matches(n,q)),addEventListener:(k,f)=>(docListeners[k]??=[]).push(f)};
const context={console,document,Intl,Date,Number,JSON,Math,Object,String,Array,Set,structuredClone,AbortController,setTimeout:()=>1,clearTimeout(){},localStorage:{getItem:k=>storage[k]||null,setItem:(k,v)=>storage[k]=v},window:{scrollTo(){},addEventListener(){},print(){}}};context.globalThis=context;
vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/math.js','utf8'),context);vm.runInContext(fs.readFileSync(__dirname+'/app.js','utf8'),context);
const fire=(el,k)=>{for(const f of el.listeners[k]||[])f({target:el});for(const f of docListeners[k]||[])f({target:el})};
return {api:context.window.HouseholdBudget,document,storage,nodes:()=>nodes,fire,el:id=>document.getElementById(id)};
}
const fixture=require('./data/sample-data.json');
let r=run();assert(r.api);assert.equal(r.api.data.transactions.length,fixture.transactions.length);assert.equal(r.api.getState().targets.dental,null);assert.equal(r.api.getState().targets.student,220);assert.equal(r.api.calculate().income,null);assert(r.el('dentalEpisodeSummary').textContent.includes('$509.00'));assert(r.el('spendingDrill').innerHTML.includes('Sample'));assert(r.el('categoryComparison').innerHTML.includes('Synthetic nonroutine example'));console.log('PASS all 5 views initialize from synthetic fixture');
r.el('planMode').value='joint';r.fire(r.el('planMode'),'change');assert.equal(r.api.calculate().income,730000);assert(r.el('forecastStatus').innerHTML.includes('pay cadence'));console.log('PASS joint mode handles illustrative cadence');
r.el('personAFrequency').value='semimonthly';r.fire(r.el('personAFrequency'),'change');r.api.setPlanInputs({currentCash:2000,cashGoal:12000,childcare:0,babyCosts:0});assert.notEqual(r.api.project().endCash,null);assert(r.el('forecastChart').innerHTML.includes('<svg'));console.log('PASS edits update forecast and chart');
r.el('forecastMonths').value='121';r.fire(r.el('forecastMonths'),'input');assert(r.el('download').disabled);assert.equal(r.el('forecastInputError').hidden,false);const preset=r.nodes().find(x=>x.dataset.horizon==='60');r.fire(preset,'click');assert.equal(r.api.getState().forecast.months,60);assert.equal(r.el('download').disabled,false);console.log('PASS invalid horizon blocks export; valid preset clears error');
r.el('category').value='Dental';r.fire(r.el('category'),'change');assert(r.el('spendingDrill').innerHTML.includes('Sample Dental Merchant'));assert(!r.el('spendingDrill').innerHTML.includes('Dining &amp; drinks'));console.log('PASS category filter changes deep drilldown');
const one=r.nodes().find(x=>x.dataset.once==='amount');one.value='-1';r.fire(one,'input');assert(r.el('download').disabled);const remove=r.nodes().find(x=>x.dataset.removeOnce==='0');r.fire(remove,'click');assert.equal(r.el('download').disabled,false);console.log('PASS removing invalid one-off restores export');
let migrated=run({version:2,targets:{medical:150,student:210,dining:125},personAPay:3200,personAFrequency:'weekly',currentCash:2500,checks:{income:true}});let state=migrated.api.getState();assert.equal(state.healthMode,'combined');assert.equal(state.targets.medical,150);assert.equal(state.targets.dental,null);assert.equal(state.targets.student,210);assert.equal(state.targets.dining,125);assert.equal(state.personAPay,3200);assert.equal(state.currentCash,2500);assert.equal(state.checks.income,true);console.log('PASS same-schema v2 scenario migration preserves edits');
let reload=run(JSON.parse(r.storage['sample-household-budget-v1-local-sample']));assert.equal(reload.api.getState().forecast.months,60);assert.equal(reload.api.getState().forecast.oneoffs.length,2);assert.equal(reload.api.getState().currentCash,2000);console.log('PASS saved scenario round trip');
for(const tab of ['overview','spending','plan','future','review']){const button=r.nodes().find(x=>x.dataset.tab===tab);r.fire(button,'click');assert.equal(r.el(tab).hidden,false);for(const other of ['overview','spending','plan','future','review'].filter(t=>t!==tab))assert.equal(r.el(other).hidden,true)}console.log('PASS each navigation button selects only its view');
r.fire(r.el('childcareQuote'),'click');assert.equal(r.api.getState().childcare,1200);assert(r.api.project().missing.includes('Childcare start month'));console.log('PASS fictitious allowance requires timing');
r.fire(r.el('reset'),'click');assert(r.el('resetDialog').open);r.fire(r.el('cancelReset'),'click');assert.equal(r.el('resetDialog').open,false);assert.equal(r.api.getState().childcare,1200);r.fire(r.el('confirmReset'),'click');assert.equal(r.api.getState().childcare,null);assert.equal(r.api.getState().tab,'overview');console.log('PASS reset cancel preserves state; confirm resets');
assert.throws(()=>r.api.setPlanInputs({personAPay:-1}));assert.throws(()=>r.api.setPlanInputs({unknown:20}));console.log('PASS public API rejects invalid fields and values');
console.log('12 simulated DOM/runtime checks passed (not a visual browser test)');
